name: Create GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    name: Build for Linux
    uses: ./.github/workflows/build-linux.yml

  build-macos:
    name: Build for macOS
    uses: ./.github/workflows/build-macos.yml

  build-macos-intel:
    name: Build for macOS Intel
    uses: ./.github/workflows/build-macos-intel.yml

  build-windows:
    name: Build for Windows
    uses: ./.github/workflows/build-windows.yml

  github-release:
    name: GitHub Release
    needs: [build-linux, build-macos, build-macos-intel, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download Linux dist
        uses: actions/download-artifact@v4
        with:
          name: linux-dist
          path: dist/
      - name: Download macOS dist
        uses: actions/download-artifact@v4
        with:
          name: macos-dist
          path: dist/
      - name: Download macOS Intel dist
        uses: actions/download-artifact@v4
        with:
          name: macos-intel-dist
          path: dist/
      - name: Download Windows dist
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist/
      - name: Create GitHub Pre-release
        if: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'dev') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --generate-notes --prerelease
      - name: Create GitHub Release
        if: ${{ !(contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'dev')) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --generate-notes
      - name: Upload dists to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'
